server.port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/xiaoqi?user=root&password=root&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username:
    password:

logging:
  level:
    org:
      springframework: INFO
      springframework.web.filter: DEBUG
      hibernate: INFO
    com:
      zaxxer.hikari: ERROR
      xiaoqi: DEBUG
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
